export enum IdentityVerificationStatus {
  NOT_STARTED = 'NOT_STARTED',
  INITIATED = 'INITIATED',
  PENDING = 'PENDING',
  AUTHENTICATED = 'AUTHENTICATED',
  DOCUMENT_FETCHING = 'DOCUMENT_FETCHING',
  VERIFIED = 'VERIFIED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CONSENT_DENIED = 'CONSENT_DENIED',
  CONSENT_EXPIRED = 'CONSENT_EXPIRED',
}

export enum IdentityMobileStatus {
  NOT_VERIFIED = 'NOT_VERIFIED',
  VERIFICATION_IN_PROGRESS = 'VERIFICATION_IN_PROGRESS',
  VERIFIED = 'VERIFIED',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
}
