export enum NotificationPlatform {
  ANDROID = 'ANDROID',
  IOS = 'IOS',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum NotificationType {
  BOOKING_RECEIVED = 'BOOKING_RECEIVED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  COMMUTE_BOOKING_REQUESTED = 'COMMUTE_BOOKING_REQUESTED',
  COMMUTE_BOOKING_CONFIRMED = 'COMMUTE_BOOKING_CONFIRMED',
  COMMUTE_BOOKING_CANCELLED = 'COMMUTE_BOOKING_CANCELLED',
  ASSURED_RIDE_PUBLISHED = 'ASSURED_RIDE_PUBLISHED',
  WALLET_CREDITED = 'WALLET_CREDITED',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
}

export enum NotificationProviderName {
  FCM = 'FCM',
  MOCK = 'MOCK',
}
